title: Software Engineer By Choice
author: arunprakashpj
email: arunprakashpj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Tech Enthusiast | Loves Java as much as I love Coffee

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  arunprakashpj  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
